version: "3"
services:
  web:
    build:
      context: thanatumFrontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://192.168.0.3:8000
    depends_on:
      - api
    networks:
      thanatum-network:
        ipv4_address: 192.168.0.4
  api:
    build:
      context: thatumBackend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=192.168.0.2
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=sys
      - APP_PORT=8000

    depends_on:
      db:
        condition: service_healthy
    networks:
      thanatum-network:
        ipv4_address: 192.168.0.3
  db:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sys
      - MYSQL_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot -e 'SHOW DATABASES;'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      thanatum-network:
        ipv4_address: 192.168.0.2

networks:
  thanatum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.1/24
