TYPE=VIEW
query=select 1 AS `host`,1 AS `statements`,1 AS `statement_latency`,1 AS `statement_avg_latency`,1 AS `table_scans`,1 AS `file_ios`,1 AS `file_io_latency`,1 AS `current_connections`,1 AS `total_connections`,1 AS `unique_users`,1 AS `current_memory`,1 AS `total_memory_allocated`
md5=5442be6e876947d5df0dfa8a1cd19576
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `host`,\n 1 AS `statements`,\n 1 AS `statement_latency`,\n 1 AS `statement_avg_latency`,\n 1 AS `table_scans`,\n 1 AS `file_ios`,\n 1 AS `file_io_latency`,\n 1 AS `current_connections`,\n 1 AS `total_connections`,\n 1 AS `unique_users`,\n 1 AS `current_memory`,\n 1 AS `total_memory_allocated`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `host`,1 AS `statements`,1 AS `statement_latency`,1 AS `statement_avg_latency`,1 AS `table_scans`,1 AS `file_ios`,1 AS `file_io_latency`,1 AS `current_connections`,1 AS `total_connections`,1 AS `unique_users`,1 AS `current_memory`,1 AS `total_memory_allocated`
