TYPE=VIEW
query=select 1 AS `host`,1 AS `statement`,1 AS `total`,1 AS `total_latency`,1 AS `max_latency`,1 AS `lock_latency`,1 AS `cpu_latency`,1 AS `rows_sent`,1 AS `rows_examined`,1 AS `rows_affected`,1 AS `full_scans`
md5=b3a05f745c47252d2951e756e72cbca6
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `host`,\n 1 AS `statement`,\n 1 AS `total`,\n 1 AS `total_latency`,\n 1 AS `max_latency`,\n 1 AS `lock_latency`,\n 1 AS `cpu_latency`,\n 1 AS `rows_sent`,\n 1 AS `rows_examined`,\n 1 AS `rows_affected`,\n 1 AS `full_scans`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `host`,1 AS `statement`,1 AS `total`,1 AS `total_latency`,1 AS `max_latency`,1 AS `lock_latency`,1 AS `cpu_latency`,1 AS `rows_sent`,1 AS `rows_examined`,1 AS `rows_affected`,1 AS `full_scans`
