TYPE=VIEW
query=select 1 AS `wait_started`,1 AS `wait_age`,1 AS `wait_age_secs`,1 AS `locked_table`,1 AS `locked_table_schema`,1 AS `locked_table_name`,1 AS `locked_table_partition`,1 AS `locked_table_subpartition`,1 AS `locked_index`,1 AS `locked_type`,1 AS `waiting_trx_id`,1 AS `waiting_trx_started`,1 AS `waiting_trx_age`,1 AS `waiting_trx_rows_locked`,1 AS `waiting_trx_rows_modified`,1 AS `waiting_pid`,1 AS `waiting_query`,1 AS `waiting_lock_id`,1 AS `waiting_lock_mode`,1 AS `blocking_trx_id`,1 AS `blocking_pid`,1 AS `blocking_query`,1 AS `blocking_lock_id`,1 AS `blocking_lock_mode`,1 AS `blocking_trx_started`,1 AS `blocking_trx_age`,1 AS `blocking_trx_rows_locked`,1 AS `blocking_trx_rows_modified`,1 AS `sql_kill_blocking_query`,1 AS `sql_kill_blocking_connection`
md5=749bcf8968d4158e869cd2b6f553aede
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `wait_started`,\n 1 AS `wait_age`,\n 1 AS `wait_age_secs`,\n 1 AS `locked_table`,\n 1 AS `locked_table_schema`,\n 1 AS `locked_table_name`,\n 1 AS `locked_table_partition`,\n 1 AS `locked_table_subpartition`,\n 1 AS `locked_index`,\n 1 AS `locked_type`,\n 1 AS `waiting_trx_id`,\n 1 AS `waiting_trx_started`,\n 1 AS `waiting_trx_age`,\n 1 AS `waiting_trx_rows_locked`,\n 1 AS `waiting_trx_rows_modified`,\n 1 AS `waiting_pid`,\n 1 AS `waiting_query`,\n 1 AS `waiting_lock_id`,\n 1 AS `waiting_lock_mode`,\n 1 AS `blocking_trx_id`,\n 1 AS `blocking_pid`,\n 1 AS `blocking_query`,\n 1 AS `blocking_lock_id`,\n 1 AS `blocking_lock_mode`,\n 1 AS `blocking_trx_started`,\n 1 AS `blocking_trx_age`,\n 1 AS `blocking_trx_rows_locked`,\n 1 AS `blocking_trx_rows_modified`,\n 1 AS `sql_kill_blocking_query`,\n 1 AS `sql_kill_blocking_connection`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `wait_started`,1 AS `wait_age`,1 AS `wait_age_secs`,1 AS `locked_table`,1 AS `locked_table_schema`,1 AS `locked_table_name`,1 AS `locked_table_partition`,1 AS `locked_table_subpartition`,1 AS `locked_index`,1 AS `locked_type`,1 AS `waiting_trx_id`,1 AS `waiting_trx_started`,1 AS `waiting_trx_age`,1 AS `waiting_trx_rows_locked`,1 AS `waiting_trx_rows_modified`,1 AS `waiting_pid`,1 AS `waiting_query`,1 AS `waiting_lock_id`,1 AS `waiting_lock_mode`,1 AS `blocking_trx_id`,1 AS `blocking_pid`,1 AS `blocking_query`,1 AS `blocking_lock_id`,1 AS `blocking_lock_mode`,1 AS `blocking_trx_started`,1 AS `blocking_trx_age`,1 AS `blocking_trx_rows_locked`,1 AS `blocking_trx_rows_modified`,1 AS `sql_kill_blocking_query`,1 AS `sql_kill_blocking_connection`
