TYPE=VIEW
query=select 1 AS `user`,1 AS `total`,1 AS `total_latency`,1 AS `min_latency`,1 AS `avg_latency`,1 AS `max_latency`,1 AS `thread_id`,1 AS `processlist_id`
md5=a855ac0806d2c504fa7e7a1f6e10085a
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `user`,\n 1 AS `total`,\n 1 AS `total_latency`,\n 1 AS `min_latency`,\n 1 AS `avg_latency`,\n 1 AS `max_latency`,\n 1 AS `thread_id`,\n 1 AS `processlist_id`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `user`,1 AS `total`,1 AS `total_latency`,1 AS `min_latency`,1 AS `avg_latency`,1 AS `max_latency`,1 AS `thread_id`,1 AS `processlist_id`
