TYPE=VIEW
query=select 1 AS `file`,1 AS `count_read`,1 AS `total_read`,1 AS `avg_read`,1 AS `count_write`,1 AS `total_written`,1 AS `avg_write`,1 AS `total`,1 AS `write_pct`
md5=701b04ac7f63da2edd81a7b5ae5817b1
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `file`,\n 1 AS `count_read`,\n 1 AS `total_read`,\n 1 AS `avg_read`,\n 1 AS `count_write`,\n 1 AS `total_written`,\n 1 AS `avg_write`,\n 1 AS `total`,\n 1 AS `write_pct`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `file`,1 AS `count_read`,1 AS `total_read`,1 AS `avg_read`,1 AS `count_write`,1 AS `total_written`,1 AS `avg_write`,1 AS `total`,1 AS `write_pct`
