TYPE=VIEW
query=select 1 AS `event_name`,1 AS `total`,1 AS `total_latency`,1 AS `avg_latency`,1 AS `max_latency`,1 AS `read_latency`,1 AS `write_latency`,1 AS `misc_latency`,1 AS `count_read`,1 AS `total_read`,1 AS `avg_read`,1 AS `count_write`,1 AS `total_written`,1 AS `avg_written`
md5=b2a3432d75f0e9e5ad9450512abf353d
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `event_name`,\n 1 AS `total`,\n 1 AS `total_latency`,\n 1 AS `avg_latency`,\n 1 AS `max_latency`,\n 1 AS `read_latency`,\n 1 AS `write_latency`,\n 1 AS `misc_latency`,\n 1 AS `count_read`,\n 1 AS `total_read`,\n 1 AS `avg_read`,\n 1 AS `count_write`,\n 1 AS `total_written`,\n 1 AS `avg_written`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `event_name`,1 AS `total`,1 AS `total_latency`,1 AS `avg_latency`,1 AS `max_latency`,1 AS `read_latency`,1 AS `write_latency`,1 AS `misc_latency`,1 AS `count_read`,1 AS `total_read`,1 AS `avg_read`,1 AS `count_write`,1 AS `total_written`,1 AS `avg_written`
