TYPE=VIEW
query=select 1 AS `host`,1 AS `current_count_used`,1 AS `current_allocated`,1 AS `current_avg_alloc`,1 AS `current_max_alloc`,1 AS `total_allocated`
md5=582b9cf056de9bdc583e2e3e0e26c243
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `host`,\n 1 AS `current_count_used`,\n 1 AS `current_allocated`,\n 1 AS `current_avg_alloc`,\n 1 AS `current_max_alloc`,\n 1 AS `total_allocated`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `host`,1 AS `current_count_used`,1 AS `current_allocated`,1 AS `current_avg_alloc`,1 AS `current_max_alloc`,1 AS `total_allocated`
