TYPE=VIEW
query=select 1 AS `object_schema`,1 AS `object_name`,1 AS `waiting_thread_id`,1 AS `waiting_pid`,1 AS `waiting_account`,1 AS `waiting_lock_type`,1 AS `waiting_lock_duration`,1 AS `waiting_query`,1 AS `waiting_query_secs`,1 AS `waiting_query_rows_affected`,1 AS `waiting_query_rows_examined`,1 AS `blocking_thread_id`,1 AS `blocking_pid`,1 AS `blocking_account`,1 AS `blocking_lock_type`,1 AS `blocking_lock_duration`,1 AS `sql_kill_blocking_query`,1 AS `sql_kill_blocking_connection`
md5=28147423be5acbeccaf909667bc097d0
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `object_schema`,\n 1 AS `object_name`,\n 1 AS `waiting_thread_id`,\n 1 AS `waiting_pid`,\n 1 AS `waiting_account`,\n 1 AS `waiting_lock_type`,\n 1 AS `waiting_lock_duration`,\n 1 AS `waiting_query`,\n 1 AS `waiting_query_secs`,\n 1 AS `waiting_query_rows_affected`,\n 1 AS `waiting_query_rows_examined`,\n 1 AS `blocking_thread_id`,\n 1 AS `blocking_pid`,\n 1 AS `blocking_account`,\n 1 AS `blocking_lock_type`,\n 1 AS `blocking_lock_duration`,\n 1 AS `sql_kill_blocking_query`,\n 1 AS `sql_kill_blocking_connection`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `object_schema`,1 AS `object_name`,1 AS `waiting_thread_id`,1 AS `waiting_pid`,1 AS `waiting_account`,1 AS `waiting_lock_type`,1 AS `waiting_lock_duration`,1 AS `waiting_query`,1 AS `waiting_query_secs`,1 AS `waiting_query_rows_affected`,1 AS `waiting_query_rows_examined`,1 AS `blocking_thread_id`,1 AS `blocking_pid`,1 AS `blocking_account`,1 AS `blocking_lock_type`,1 AS `blocking_lock_duration`,1 AS `sql_kill_blocking_query`,1 AS `sql_kill_blocking_connection`
