TYPE=VIEW
query=select 1 AS `table_schema`,1 AS `table_name`,1 AS `total_latency`,1 AS `rows_fetched`,1 AS `fetch_latency`,1 AS `rows_inserted`,1 AS `insert_latency`,1 AS `rows_updated`,1 AS `update_latency`,1 AS `rows_deleted`,1 AS `delete_latency`,1 AS `io_read_requests`,1 AS `io_read`,1 AS `io_read_latency`,1 AS `io_write_requests`,1 AS `io_write`,1 AS `io_write_latency`,1 AS `io_misc_requests`,1 AS `io_misc_latency`
md5=a3c03640b5a63402fdfbb0d728729bc0
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `table_schema`,\n 1 AS `table_name`,\n 1 AS `total_latency`,\n 1 AS `rows_fetched`,\n 1 AS `fetch_latency`,\n 1 AS `rows_inserted`,\n 1 AS `insert_latency`,\n 1 AS `rows_updated`,\n 1 AS `update_latency`,\n 1 AS `rows_deleted`,\n 1 AS `delete_latency`,\n 1 AS `io_read_requests`,\n 1 AS `io_read`,\n 1 AS `io_read_latency`,\n 1 AS `io_write_requests`,\n 1 AS `io_write`,\n 1 AS `io_write_latency`,\n 1 AS `io_misc_requests`,\n 1 AS `io_misc_latency`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `table_schema`,1 AS `table_name`,1 AS `total_latency`,1 AS `rows_fetched`,1 AS `fetch_latency`,1 AS `rows_inserted`,1 AS `insert_latency`,1 AS `rows_updated`,1 AS `update_latency`,1 AS `rows_deleted`,1 AS `delete_latency`,1 AS `io_read_requests`,1 AS `io_read`,1 AS `io_read_latency`,1 AS `io_write_requests`,1 AS `io_write`,1 AS `io_write_latency`,1 AS `io_misc_requests`,1 AS `io_misc_latency`
