TYPE=VIEW
query=select 1 AS `table_schema`,1 AS `table_name`,1 AS `redundant_index_name`,1 AS `redundant_index_columns`,1 AS `redundant_index_non_unique`,1 AS `dominant_index_name`,1 AS `dominant_index_columns`,1 AS `dominant_index_non_unique`,1 AS `subpart_exists`,1 AS `sql_drop_index`
md5=979220b7b1381fb327134d1c6c4b204a
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `table_schema`,\n 1 AS `table_name`,\n 1 AS `redundant_index_name`,\n 1 AS `redundant_index_columns`,\n 1 AS `redundant_index_non_unique`,\n 1 AS `dominant_index_name`,\n 1 AS `dominant_index_columns`,\n 1 AS `dominant_index_non_unique`,\n 1 AS `subpart_exists`,\n 1 AS `sql_drop_index`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `table_schema`,1 AS `table_name`,1 AS `redundant_index_name`,1 AS `redundant_index_columns`,1 AS `redundant_index_non_unique`,1 AS `dominant_index_name`,1 AS `dominant_index_columns`,1 AS `dominant_index_non_unique`,1 AS `subpart_exists`,1 AS `sql_drop_index`
