TYPE=VIEW
query=select 1 AS `thread_id`,1 AS `ssl_version`,1 AS `ssl_cipher`,1 AS `ssl_sessions_reused`
md5=a0d4dba54ae629a87573912f4bb59dbc
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `thread_id`,\n 1 AS `ssl_version`,\n 1 AS `ssl_cipher`,\n 1 AS `ssl_sessions_reused`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `thread_id`,1 AS `ssl_version`,1 AS `ssl_cipher`,1 AS `ssl_sessions_reused`
