TYPE=VIEW
query=select 1 AS `query`,1 AS `db`,1 AS `exec_count`,1 AS `total_latency`,1 AS `sort_merge_passes`,1 AS `avg_sort_merges`,1 AS `sorts_using_scans`,1 AS `sort_using_range`,1 AS `rows_sorted`,1 AS `avg_rows_sorted`,1 AS `first_seen`,1 AS `last_seen`,1 AS `digest`
md5=5112b1eece60fe8d1917598b93979743
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `query`,\n 1 AS `db`,\n 1 AS `exec_count`,\n 1 AS `total_latency`,\n 1 AS `sort_merge_passes`,\n 1 AS `avg_sort_merges`,\n 1 AS `sorts_using_scans`,\n 1 AS `sort_using_range`,\n 1 AS `rows_sorted`,\n 1 AS `avg_rows_sorted`,\n 1 AS `first_seen`,\n 1 AS `last_seen`,\n 1 AS `digest`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `query`,1 AS `db`,1 AS `exec_count`,1 AS `total_latency`,1 AS `sort_merge_passes`,1 AS `avg_sort_merges`,1 AS `sorts_using_scans`,1 AS `sort_using_range`,1 AS `rows_sorted`,1 AS `avg_rows_sorted`,1 AS `first_seen`,1 AS `last_seen`,1 AS `digest`
