TYPE=VIEW
query=select 1 AS `query`,1 AS `db`,1 AS `full_scan`,1 AS `exec_count`,1 AS `err_count`,1 AS `warn_count`,1 AS `total_latency`,1 AS `max_latency`,1 AS `avg_latency`,1 AS `rows_sent`,1 AS `rows_sent_avg`,1 AS `rows_examined`,1 AS `rows_examined_avg`,1 AS `first_seen`,1 AS `last_seen`,1 AS `digest`
md5=b8b5401b42ab27e39413d2b3fa0182c9
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-04-08 15:57:05
create-version=1
source=SELECT \n 1 AS `query`,\n 1 AS `db`,\n 1 AS `full_scan`,\n 1 AS `exec_count`,\n 1 AS `err_count`,\n 1 AS `warn_count`,\n 1 AS `total_latency`,\n 1 AS `max_latency`,\n 1 AS `avg_latency`,\n 1 AS `rows_sent`,\n 1 AS `rows_sent_avg`,\n 1 AS `rows_examined`,\n 1 AS `rows_examined_avg`,\n 1 AS `first_seen`,\n 1 AS `last_seen`,\n 1 AS `digest`
client_cs_name=utf8mb4
connection_cl_name=utf8_general_ci
view_body_utf8=select 1 AS `query`,1 AS `db`,1 AS `full_scan`,1 AS `exec_count`,1 AS `err_count`,1 AS `warn_count`,1 AS `total_latency`,1 AS `max_latency`,1 AS `avg_latency`,1 AS `rows_sent`,1 AS `rows_sent_avg`,1 AS `rows_examined`,1 AS `rows_examined_avg`,1 AS `first_seen`,1 AS `last_seen`,1 AS `digest`
